default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: payment_system_api_development

test:
  <<: *default
  database: payment_system_api_test

production:
  <<: *default
  url: <%= ENV["PAYMENT_SYSTEM_API_DATABASE_URL"] %>
  pool: 5
  timeout: 5000